
-- two sample users
-- both have password set to 'password'
INSERT INTO users (username, password, email, is_admin)
VALUES ('admin',
        '$2b$12$AZH7virni5jlTTiGgEg4zu3lSvAw68qVEfSIOjJ3RqtbJbdW/Oi5q',
        'admin@email.com', TRUE),
        ('mathguy',
        '$2b$12$YAN6T0baGrdSMFYwUsFF9.a6prxvDRYRDPAF5i/zOvjqDiB.zSuVC',
        'mathguy@email.com', FALSE),
        ('the_humanities',
        '$2b$12$nOvZSUtf.x7FZEPfIqKHVu399VF49SsCVlyjiGQJWyZAqjH0LaDUS',
        'the_humanities@email.com', FALSE);

-- sample quizzes
INSERT INTO quizzes (id, title, description, creator, is_public)
VALUES (1, 'Shapes Quiz', 'A fun sample quiz about shapes!', 'mathguy', TRUE),
       (2, 'US States', 'Trivia quiz about US states!', 'the_humanities', TRUE),
       (3, 'Spelling', 'Choose the word that has been spelled incorrectly!', 'the_humanities', TRUE),
       (4, 'Solving Equations', 'work in progress...', 'mathguy', FALSE),
       (5, 'Analogies', 'work in progress...', 'the_humanities', FALSE);

-- sample questions
INSERT INTO questions ( q_text,
                        right_a,
                        wrong_a1,
                        wrong_a2,
                        wrong_a3,
                        quiz_id)
VALUES
        -- QUIZ ONE: GEOMETRY
        ('What is the sum of the interior angles of a triangle?',
            '180 degrees',
            '90 degrees',
            '360 degrees',
            '270 degrees',
            1),
        ('The angles of a rectangle each measure...',
            '90 degrees',
            '60 degrees',
            '45 degrees',
            '30 degrees',
            1),
        ('A hexagon has how many sides?',
            '6 sides',
            '4 sides',
            '5 sides',
            '8 sides',
            1),
        ('Lines that never intersect are called...',
            'parallel',
            'perpendicular',
            'skew',
            'obtuse',
            1),
        ('Two angles that sum to 180 degrees are called...',
            'supplementary',
            'complementary',
            'acute',
            'obtuse',
            1),
        -- QUIZ TWO: US STATES
        ('Which US state has the longest coastline?',
            'Alaska',
            'California',
            'Hawaii',
            'Florida',
            2),
        ('What is the only letter that does not appear in a state name?',
            'Q',
            'X',
            'J',
            'Z',
            2),
        ('How many islands make up the state of Hawaii?',
            '137',
            '42',
            '8',
            '5',
            2),
        -- QUIZ THREE: SPELLING
        ('Which word is spelled CORRECTLY?',
            'transient',
            'transeint',
            'transent',
            'transint',
            3),
        ('Which word is spelled CORRECTLY?',
            'heritage',
            'heratage',
            'heretage',
            'heiritage',
            3),
        ('Which word (if any) is misspelled?',
            'ocassionaly',
            'necessarily',
            'recommended',
            'all of the other words are correct',
            3),
        ('Which word (if any) is misspelled?',
            'all of the other words are correct',
            'pleasure',
            'measure',
            'leisure',
            3),
        ('Which word is spelled INCORRECTLY?',
            'irelevant',
            'mediocrity',
            'dilapidated',
            'derogatory',
            3),
        -- QUIZ FOUR: ALGEBRA
        ('3x + 1 = 16',
            'x = 5',
            'x = 6',
            'x = 17/3',
            'x = 13/3',
            4),
        ('2x - 7 = 13',
            'x = 10',
            'x = 3',
            'x = -10',
            'x = -3',
            4),
        -- QUIZ FIVE: ANALOGIES
        ('End is to abolish as begin is to...',
            'establish',
            'finish',
            'tyrrany',
            'monarchy',
            5), 
        ('Finger is to hand as...',
            'strand is to hair',
            'arm is to sleeve',
            'leg is to foot',
            'shoe is to foot',
            5);

-- sample quiz scores for testuser
INSERT INTO users_quizzes (username, quiz_id, last_score, best_score, time_taken)
    VALUES ('mathguy', 1, 5, 5, '1999-01-08 04:05:06'),
           ('mathguy', 2, 1, 2, '2004-10-19 10:23:54'),
           ('mathguy', 3, 3, 3, '2022-06-23 15:46:37');
